from .elemento import Equipo
from .decorativo import EquipoDecorativo
from .electronico import EquipoElectronico
from .escritorio import EquipoEscritorio
from .herramienta import EquipoHerramienta
from .iluminacion import EquipoIluminacion
from .limpieza import EquipoLimpieza
from .seguridad import EquipoSeguridad
from .silla import EquipoSilla
from .otro import EquipoOtro
